services:
  # Development PostgreSQL
  postgres_dev:
    image: postgres:latest
    container_name: postgres_dev
    environment:
      POSTGRES_DB: ${DEV_DB_NAME}
      POSTGRES_USER: ${DEV_DB_USER}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
    ports:
      - "${DEV_DB_PORT}:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - spring_task_net

  # Test PostgreSQL
  postgres_test:
    image: postgres:latest
    container_name: spring_task_postgres_test
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
    ports:
      - "${TEST_DB_PORT}:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - spring_task_net

  # Production PostgreSQL
  postgres_prod:
    image: postgres:latest
    container_name: spring_task_postgres_prod
    environment:
      POSTGRES_DB: ${PROD_DB_NAME}
      POSTGRES_USER: ${PROD_DB_USER}
      POSTGRES_PASSWORD: ${PROD_DB_PASSWORD}
    ports:
      - "${PROD_DB_PORT}:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    networks:
      - spring_task_net

volumes:
  postgres_dev_data:
  postgres_test_data:
  postgres_prod_data:

networks:
  spring_task_net:
    driver: bridge

