spring:
  datasource:
    url: jdbc:postgresql://${TEST_DB_HOST}:${TEST_DB_PORT}/${TEST_DB_NAME}
    username: ${TEST_DB_USER}
    password: ${TEST_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop  # Reset DB after tests
    show-sql: false
  sql:
    init:
      mode: always
      data-locations: classpath:data-test.sql
