spring:
  profiles:
    active: dev
  security:
    user:
      name: user
      password: user
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SUPPORT_EMAIL}
    password: ${SUPPORT_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: NEVER
    flyway:
      access: unrestricted

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
    org.flywaydb: DEBUG

jwt:
  jwt-secret: ${JWT_SECRET}
  access-token-expiration-time: ${JWT_EXPIRATION}
  refresh-token-expiration-time: ${JWT_REFRESH_TOKEN}
