spring:
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: NEVER
    flyway:
      access: unrestricted

jwt:
  secret: ${JWT_SECRET} # Use environment variable in production
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_TOKEN}
