spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # Never auto-create tables in prod
    show-sql: false
  sql:
    init:
      mode: never  # Disable auto-initialization in prod
logging:
  level:
    root: WARN
    dev.amirgol.springtaskbackend: INFO   # Less verbose in production
  file:
    name: logs/app.log              # Log to file in production
