spring:
  profiles:
    active: dev
  security:
    user:
      name: user
      password: user
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SUPPORT_EMAIL}
    password: ${SUPPORT_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# DGS should be at root level, NOT under spring
dgs:
  graphql:
    graphiql:
      enabled: true
    path: /graphql

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: NEVER
    flyway:
      access: unrestricted
minio:
  endpoint: http://localhost:9000
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
  bucket: attachments

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
    org.flywaydb: DEBUG
    com.netflix.graphql.dgs: DEBUG

jwt:
  jwt-secret: ${JWT_SECRET}
  access-token-expiration-time: ${JWT_EXPIRATION}
  refresh-token-expiration-time: ${JWT_REFRESH_TOKEN}